### ISSUE TITLE
Doesn't seem to implement org.freedesktop.DBus.Introspectable

### ISSUE THREAD

**Issue by FichteFoll** [natsukagami/mpd-mpris#1]
The `org.freedesktop.DBus.Introspectable` interface is used by some applications to discover the interfaces provided by an object. While the `org.mpris.MediaPlayer2` and `org.mpris.MediaPlayer2.Player` interfaces of mpd-mpris are implemented and can be called, they cannot be discovered on the object as it's not introspectable.

[dbussy](https://github.com/ldo/dbussy) relies on this to provide a dynamic auto-proxy, for example. There are also tools like qdbusviewer (included in qt5-tools for example) to view available busses, their objects and the interfaces they provide.

**Comment by FichteFoll** [comment]
Following are screenshots from qdbusviewer showing the mpris busses of mpd-mpris and mpv-mpris:

![2018-04-16_20-37-44](https://user-images.githubusercontent.com/931051/38828394-38e0053c-41b6-11e8-821f-e40f4353ff86.png)
![2018-04-16_20-38-07](https://user-images.githubusercontent.com/931051/38828395-39009716-41b6-11e8-9e2e-e7929609fa0a.png)

**Comment by FichteFoll** [comment]
I discovered https://github.com/eonpatapon/mpDris2 now, which implements the interface, so I'll be using that from now onwards. I'll leave the issue open for you to decide on what to do with it.

**Comment by natsukagami** [comment]
Thanks for the report! I'm new to this DBus implementation, so I don't know much about the details.

It seems that the said interface could be easily implemented by just a call to `go-dbus` library (which is the one I am using already), so it should be fixed quickly. 

Unfortunately I am away at the moment, but I'll get to it as soon as I could.

**Comment by natsukagami** [comment]
I've implemented it (roughly, I suppose?), please take a moment to check it out if you still have intentions of using `mpd-mpris`.
