### ISSUE TITLE
Volume gets set to zero after unlocking the session on GNOME

### ISSUE THREAD

**Issue by guihkx** [natsukagami/mpd-mpris#15]
My session locks automatically after 10 minutes, and I noticed that after unlocking it, mpd always gets muted.

How to reproduce (tested on GNOME 3.18.1):

1. Leave any song playing on mpd
2. Hit <kbd>Super</kbd>+<kbd>L</kbd> to lock the session
3. Type your password and unlock the session

After that, mpd-mpris will set mpd's volume to zero:

```
$ journalctl -b
[...]
nov 16 18:28:08 arch gdm-password][11530]: gkr-pam: unlocked login keyring
nov 16 18:28:10 arch mpd-mpris[4020]: 2020/11/16 18:28:10 Shuffle changed to true
nov 16 18:28:10 arch mpd-mpris[4020]: 2020/11/16 18:28:10 Volume changed to 56
nov 16 18:28:10 arch mpd-mpris[4020]: 2020/11/16 18:28:10 Shuffle changed to false
nov 16 18:28:10 arch mpd-mpris[4020]: 2020/11/16 18:28:10 LoopStatus changed to Track
nov 16 18:28:10 arch mpd-mpris[4020]: 2020/11/16 18:28:10 LoopStatus changed to Playlist
nov 16 18:28:10 arch mpd-mpris[4020]: 2020/11/16 18:28:10 Volume changed to 0
[...]
```

**Comment by natsukagami** [comment]
Very interesting. Does it happen on other MPRIS-supported players? (try Rhythmbox for example)

**Comment by guihkx** [comment]
>Does it happen on other MPRIS-supported players

Nope...

FWIW, I was using [mpDris2](https://github.com/eonpatapon/mpDris2) for a long time and this doesn't happen there either. I gave up on it for other reasons though and now I'm giving mpd-mpris a try. :P

**Comment by natsukagami** [comment]
That log looks very chaotic! I'll take a look at GNOME to see if I can reproduce

**Comment by guihkx** [comment]
Thanks! There's this other odd behavior with playback flags too, I think. But I'm not sure if it's somewhat intentional, so please let me know if you want me to open a new issue:

Basically, I mostly use ncmpcpp to control mpd, and I don't like to leave any of these playback flags enabled:

![image](https://user-images.githubusercontent.com/626206/99371596-de54ad80-289d-11eb-83fd-effadd18b39b.png)

However, if I keep restarting the mpd-mpris service, those flags seem to randomly enable/disable themselves. I recorded a video of this behavior as well, just in case:

https://streamable.com/ndrrjq

**Comment by natsukagami** [comment]
Sorry, I could not reproduce it either on GNOME or with ncmpcpp... I really wonder what's going on there. Maybe a player add-on for GNOME? Does it happen on other desktop environments?

**Comment by guihkx** [comment]
>Maybe a player add-on for GNOME?

Sh*t, I should've tested with all my extensions disabled before opening a new issue. I do indeed use this extension called [Mpris indicator button](https://extensions.gnome.org/extension/1379/mpris-indicator-button/). After disabling it, mpv-mpris doesn't mute mpd after unlocking the session.

I wonder why this doesn't happen with mpDris2 though. :(

Regardless, as this doesn't seem to be mpd-mpris' fault, let me close this one. Sorry!

**Comment by natsukagami** [comment]
@guihkx, if you ever wanted to open an issue on their side (https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button), feel free to ping me. This might really be something related to `mpd-mpris`, and I would be willing to co-operate for a fix.

**Comment by guihkx** [comment]
Will do it later, thanks!
