### ISSUE TITLE
Compatibility with `playerctld`

### ISSUE THREAD

**Issue by Silipwn** [natsukagami/mpd-mpris#24]
Hi, I use this program with couple of other media players as well. 
Playerctld is a feature introduced to detect the "last active player".
I was wondering if mpd-mpris is compatible with that.

**Comment by Eluminae** [comment]
I dunno what is preventing mpd-mpris to be playerctld compatible but that annoy me too. 

Is there any news on it ? Someone already got knowledge to dig into it ?

**Comment by Eluminae** [comment]
I think that mpd-mpris continiously talk to playerctld (contrary to mpv-mpris) which probably is part of the issue. playerctld must think it is pretty active

**Comment by natsukagami** [comment]
Sorry for taking so long to come back to this. I am implementing something that fixes this issue in #34. Would be nice if you want to try it out!

**Comment by stacyharper** [comment]
To be fair, it seems it works now. Or at least, I'm not sure how to reproduce the issues I had back o_O
Playerd seems to correctly use the "last-active" player. Did you change something in between?

**Comment by natsukagami** [comment]
I didn't really change much on the `master` branch, other than making `mpd-mpris` push for updates less :D

**Comment by stacyharper** [comment]
Maybe it was enough :D Anyway if #34 still is better, don't frustrate yourself

**Comment by acid-bong** [comment]
I installed 0.4.0 (came out before #34 was merged), and it works both with running playerctld and without it. I assume it was fixed even earlier, somewhere before 0.4.0
