### ISSUE TITLE
Release it as a precompiled binary on github

### ISSUE THREAD

**Issue by m040601** [natsukagami/mpd-mpris#26]
Thanks for your work providing this tool.
I havent had the chance to test it, but I really want because the one I am currently
using with mpd is quite buggy.

Not wanting to be to demanding but, any chance you could actualy release it as a binary on github ?

It's not practical for non developers to constantly download the half giga go distro and recompile go binaries.

On low powered ARM devices like a Raspberry Pi running mpd it's not practical to be constantly recompiling go .

Releasing a binary, just makes your tool available for someone who just wants to check it out quickly, compare it with others.

Not everyone has or wants the entire go distribution installed or as a simple user is familiar with compiling.Besides that releasing a binary, would make it easier for others to create a package for a Linux distro, based on the binary (ex. Ubuntu, Archlinux AUR).

I see you are an Arch Linux user, https://aur.archlinux.org/packages/mpd-mpris/
It would be so nice to have a mpd-mpris-bin PKGBUILD based  on the github released binary.

Do you know you can automate this for free with github actions ?

Check how other famous go tools do it, for example https://github.com/gokcehan/lf/tree/master/.github/workflows

Do you also know this tool, https://github.com/goreleaser/goreleaser ? https://goreleaser.com/ci/actions/ ?

Thanks in advance

**Comment by natsukagami** [comment]
Thanks for the issue. Yes, I am aware of GitHub Actions; I just wasn’t
really having the free time to set it up. Given that I am on a Macbook now
this tool isn’t really on my machine for the time being, I also didn’t have
the incentive to polish this :(

I’ll look into it sometime this week.

**Comment by natsukagami** [comment]
Sorry for the late reply. I made the last release binaries fully available, but haven't set up a CI pipeline to do this yet.

**Comment by m040601** [comment]
Thank you so much.


Since you are also the maintainer of, https://aur.archlinux.org/packages/mpd-mpris/,, could you please also provide a mpd-mpris-bin PKGBUILD . Thank you.

**Comment by m040601** [comment]
And about arm binary releases.
I'm not a programmer or developer, so please correct me if I'm wrong.

I see on the releases page:

`mpd-mpris_0.3.1_Linux_arm64.tar.gz`


This "arm64" means it's only for 64bit arm right ? Like the Raspberry Pi 4.


This means 32bit only Raspberry Pi models prior to the Rpi3 are not supported.
That leaves a lot of Rpi2 and Rpi zeros behind.

I, like many others, run mpd on a perfectly capable Rpi2 v1.1 (armv7h, does not support aarch64). The same for the Raspberry Pi zero (armv6).
It's a pity because these devices work faboulosly with Arch Linux ARM with many other go software.


Ex, https://github.com/Jguer/yay/releases.
Usually the PKGBUILD only needs a small change in "arch":


`arch=('x86_64' 'aarch64' 'armv6h' 'armv7h')`


Could you make it so to guarantee that besides 64 bit arm other arm binaries are compiled. I believe you only need 2. One for arm 64, and one "universal" for all the others.

**Comment by natsukagami** [comment]
Sorry for taking so long, but https://aur.archlinux.org/packages/mpd-mpris-bin should satisfy your needs!
