### ISSUE TITLE
Cover stuck at first song

### ISSUE THREAD

**Issue by xeruf** [natsukagami/mpd-mpris#28]
Thanks for the great work :)

Unfortunately, at least for me, the cover shown is always the cover of the first song played at startup, not updating on song change.

**Comment by natsukagami** [comment]
Interesting. I haven't been using `mpd` itself lately, so it's kinda hard to debug stuff like this D:

**Comment by coxackie** [comment]
I am having the same issue - cover is stuck at the album of the first song played. (Using GNOME, but I do not think this is in any way relevant.) Not a huge problem, but it would be nice if this was somehow addressed.

**Comment by xeruf** [comment]
It is same for me on KDE Plasma. Maybe some update event needs to be sent?

**Comment by natsukagami** [comment]
Something that comes to mind is that I am using the same file for album art 
https://github.com/natsukagami/mpd-mpris/blob/63cc6e82e971f15cc6f03633773495481bcd4c33/mpd/song.go#L23-L25

So it might be the case that GNOME/Plasma just doesn't try to reload the album art since the URL is the same.

**Comment by coxackie** [comment]
@natsukagami what if upon every song change the temp URL is given a different (for example, random) name? would this be possible? maybe it can help.

**Comment by xeruf** [comment]
yep, just generate a new temp file everytime and it should work :)

**Comment by coxackie** [comment]
let hope @natsukagami is going to implement this!

**Comment by natsukagami** [comment]
@xeruf @coxackie would you mind testing out #30? I don't have a MPRIS-compatible device to test at the moment

**Comment by coxackie** [comment]
@xeruf are you able to test this? I am at the moment away from my main desktop where I can compile go.

**Comment by coxackie** [comment]
@natsukagami so, I actually compiled branch `random-artwork-name`, and it does not seem to resolve the issue in GNOME. but let us also wait to hear from @xeruf

**Comment by xeruf** [comment]
Not sure on this so far. One thing it still does not recognize is folder-artwork, curiously there is some service on my machine now that works regardless.
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/13354331/144589419-42eafbf7-f9a2-46d6-a0f7-7edcf67d5eee.png">

**Comment by xeruf** [comment]
Uh it's https://github.com/eonpatapon/mpDris2 that is showing notifications and stuff I think. Hmm.

**Comment by natsukagami** [comment]
Let me have a look at how mpDris2 does it ;)

**Comment by coxackie** [comment]
@natsukagami thanks - if you get another idea, please let us know and we can try it out.

**Comment by natsukagami** [comment]
@coxackie So I finally got a Linux machine to test things out with (I am on a fairly vanilla NixOS machine atm), and running on #30 branch is working on GNOME for me. 

Well, actually I don't really know what GNOME extension you might be using... But the default "music player status" seems to work for me.

**Comment by natsukagami** [comment]
> Not sure on this so far. One thing it still does not recognize is folder-artwork, curiously there is some service on my machine now that works regardless. <img alt="image" width="1274" src="https://user-images.githubusercontent.com/13354331/144589419-42eafbf7-f9a2-46d6-a0f7-7edcf67d5eee.png">

For this, I will need to implement something that actually goes in and find the files on your system (kind of similar to the other open issue #29). I made this tool with no intention of touching the filesystem at all (I use it for a remote `mpd` instance, so no way it could fetch actual mp3 or any other artwork files), but it seems like there's enough demand to integrate it after all.

**Comment by RensOliemans** [comment]
It works! I'm on branch `random-artwork-name`, you can see in the screenshot below that the `mpris:artUrl` changes.

![2023-03-06T21:31:41,589027945+01:00](https://user-images.githubusercontent.com/16014817/223223874-14128019-0960-4e96-957c-4f940b280a53.png)

Thanks! If there's anything else I need to test, please let me know :+1:

**Comment by natsukagami** [comment]
Thanks, lemme just merge the branch then :P

**Comment by RensOliemans** [comment]
Awesome, thanks!
