### ISSUE TITLE
Empty value for url

### ISSUE THREAD

**Issue by lhupitr** [natsukagami/mpd-mpris#29]
mpd-mpris doesn't seem to be able to return the url (xesam:url):

> playerctl --player mpd metadata  
> mpd   xesam:trackNumber   
> mpd   xesam:title      
> mpd   xesam:contentCreated 
> mpd   xesam:artist    
> mpd   xesam:albumArtist    
> mpd   xesam:genre
> mpd   mpris:trackid   
> mpd   mpris:length   
> mpd   xesam:album

**Comment by natsukagami** [comment]
This is because `mpd-mpris` actually doesn't know where the file is. Afaik I can only get the path to the file relative to the music directory settings in `mpd`, and I don't want to intrude `mpd`'s configuration file and read the `music_directory` from there.

**Comment by lhupitr** [comment]
How about a command line option to set the music directory?

**Comment by natsukagami** [comment]
This actually has been implemented in 8b5243a6 (#14)
