### ISSUE TITLE
Inconsistant name

### ISSUE THREAD

**Issue by concatime** [natsukagami/mpd-mpris#3]
Hi. I want to have a fixed `org.mpris.MediaPlayer2.mpd`, not `org.mpris.MediaPlayer2.mpd.instanceXXX`. How do I achieve this?

**Comment by natsukagami** [comment]
I can implement the behaviour if you want.

**Comment by concatime** [comment]
That would be neat!

**Comment by natsukagami** [comment]
Please try it out!
