### ISSUE TITLE
Socket support

### ISSUE THREAD

**Issue by bergentroll** [natsukagami/mpd-mpris#7]
Seems does not work with file socket setup. When `bind_to_address "~/.config/mpd/socket"` in ~/.config/mpd/mpd.conf specified, I've got on mpd-mpris run:

```
panic: dial tcp: lookup /home/anton/.config/mpd/socket: no such host

goroutine 1 [running]:
main.main()
	/home/anton/build/mpd-mpris/src/mpd-mpris-0.2.3/cmd/mpd-mpris/main.go:62 +0x65b
```

**Comment by natsukagami** [comment]
Hi @bergentroll, sorry for the very late response... I've tried implementing the option in #8, please check it out and give me a thumbs up if it works!

**Comment by bergentroll** [comment]
@natsukagami 🖒
It works indeed, thank you!

**Comment by bergentroll** [comment]
@natsukagami 🖒
It works indeed, thank you!
