### ISSUE TITLE
Feature request: URL in mpris attribute xesam:url

### ISSUE THREAD

**Issue by hifiberry** [natsukagami/mpd-mpris#9]
Hi,

First: Thank you for this tool that we're using in HiFiBerryOS. It works very well and stable.

One thing we're missing at the moment is the file name and/or URL of the current song. This would fit perfectly into the xesam:url MPRIS 

MPC gives this information in the "file" attribute:
mpc -f %file% current
http://addrad.io/444y3fj

While I can try to add this by myself, it will probably take me a long time to do this as I never did anything in Go. Maybe you already have an idea how to do this and it's just a 2-liner (not sure about this). What do you think?

Best regards,
Daniel

**Comment by natsukagami** [comment]
Hi @hifiberry, 

Wow, thank you for using this! I really didn't know I had such a huge user. 
About the tag, I will look into adding it. I don't think it would take more than a few lines to implement. 
Please look forward to it.

**Comment by hifiberry** [comment]
Cool - that did the trick!
Thank you. 

BTW: We're not that big ;-)
If you don't own a HiFiBerry already, drop me a message.

**Comment by natsukagami** [comment]
Thanks for notifying! 
I also dropped an email to info@hifiberry.com, please check it out.
